### ISSUE TITLE
Add Tianpower TP-LT55 support (used in BASEN 48V 200Ah battery packs)

### ISSUE THREAD

**Issue by xpinguinx** [syssi/esphome-tianpower-bms#1]
Is it possible to develop this same ESPHome component to monitor a 48Volt Basen BMS via the Bluetooth port and receive data in MQTT??

I tried to use "esp32-ble-example.yaml" and through the MQTT-EXPLORER debug application I see that the ESP32 connects to the BMS:

""**[0;35m[C][mqtt.switch:041]: MQTT Switch 'basen-bms-ble enable bluetooth connection': [0m**

but after a few seconds it disconnects displaying this other error: 
**[0;33m[W][basen_bms_ble:213]: [A4:C1:38:27:48:9A] Not connected [0m**

I note that the "switch" topics are displayed correctly in the MQTT brocker while the "sensors" of the cells, temperatures and everything else are not displayed.

I trust in your help, thank you

**Comment by xpinguinx** [comment]
I absolutely have to solve the bluetooth communication problem by exporting the data and sensors in the MQTT format.
Can you please tell me what I should do and how long it takes for this job? 
Can we talk in private? 
Thank you

**Comment by syssi** [comment]
I've pushed a first draft of the tianpower protocol implementation. Please flash this YAML

https://github.com/syssi/esphome-tianpower-bms/blob/main/esp32-ble-example.yaml

and provide a ESPHome log. The log can be retrieve using the ESPhome CLI:

```
esphome logs esp32-ble-example.yaml
```

**Comment by syssi** [comment]
Could you check the Android app. Are there switches / button to control the mosfet state (charging on/off, discharging on/off)? Could you provide some screenshots of the different views of the Android app?

**Comment by xpinguinx** [comment]
> Puoi controllare l'app per Android. Ci sono interruttori/pulsanti per controllare lo stato del mosfet (carica on/off, scarica on/off)? Puoi fornire alcuni screenshot delle diverse visualizzazioni dell'app per Android?

![Image 1](https://github.com/syssi/esphome-tianpower-bms/assets/19188638/468f064c-7469-40a1-89aa-c4b2d0ad5d11)
![Image 2](https://github.com/syssi/esphome-tianpower-bms/assets/19188638/81506716-a9cf-4d33-bb42-6c1a816ab7fa)
![Image 3](https://github.com/syssi/esphome-tianpower-bms/assets/19188638/09656ead-3fc3-4a15-b013-6757dff4b6f1)
![Image 4](https://github.com/syssi/esphome-tianpower-bms/assets/19188638/503731ec-99ec-40a1-986a-b9718fcc6a5b)
![Image 5](https://github.com/syssi/esphome-tianpower-bms/assets/19188638/c98a2fe6-310a-49ba-9948-51e5a6c7573f)

[logs_tianpowerbms_compile.txt](https://github.com/syssi/esphome-tianpower-bms/files/11643028/logs_tianpowerbms_compile.txt)

**Comment by xpinguinx** [comment]
> Could you check the Android app. Are there switches / button to control the mosfet state (charging on/off, discharging on/off)? Could you provide some screenshots of the different views of the Android app?

[Image 1.zip](https://github.com/syssi/esphome-tianpower-bms/files/11643040/Image.1.zip)
[Image 2.zip](https://github.com/syssi/esphome-tianpower-bms/files/11643041/Image.2.zip)
[Image 3.zip](https://github.com/syssi/esphome-tianpower-bms/files/11643042/Image.3.zip)
[Image 4.zip](https://github.com/syssi/esphome-tianpower-bms/files/11643043/Image.4.zip)
[logs_tianpowerbms_compile.zip](https://github.com/syssi/esphome-tianpower-bms/files/11643044/logs_tianpowerbms_compile.zip)

**Comment by syssi** [comment]
I've pushed a fixed version of the YAML configuration.

**Comment by syssi** [comment]
The current implementation should be able to connect to the BMS and subscribe to some notification streams. The received raw data should be printed to the log. Please provide such a log. As soon as we are sure everything works as expected we can move on.

**Comment by xpinguinx** [comment]
fails to finish compiling "esp32-ble-example.yaml" (error log file attached)

[logs_tianpowerbms_compile (1).txt](https://github.com/syssi/esphome-tianpower-bms/files/11643263/logs_tianpowerbms_compile.1.txt)

**Comment by syssi** [comment]
A clean build is required:

```
esphome clean esp32-ble-example.yaml
esphome run esp32-ble-example.yaml
```

If you use the ESPHome dashboard there should be a "clean build" button.

**Comment by xpinguinx** [comment]
> 

...with which procedure and how should I export the logs?
debug MQTT I see this result

![log-MQTT](https://github.com/syssi/esphome-tianpower-bms/assets/19188638/128a36a1-79a8-4965-b400-87ce93688e0d)

**Comment by syssi** [comment]
Do you use the ESPHome dashboard? If you click on a ESPHome node and choose the "log" button you should be able to copy&paste the log. A log capture of around 1-3 minutes would be nice.

**Comment by xpinguinx** [comment]
> Usi la dashboard di ESPHome? Se fai clic su un nodo ESPHome e scegli il pulsante "log", dovresti essere in grado di copiare e incollare il log. Un'acquisizione del registro di circa 1-3 minuti sarebbe utile.

Attached the log. Good work :)

[logs.txt](https://github.com/syssi/esphome-tianpower-bms/files/11643423/logs.txt)

**Comment by syssi** [comment]
I've pushed another change. In best case the component is able to decode and publish some measurements now via MQTT. Could you flash your device again and provide another log?

**Comment by xpinguinx** [comment]
Unfortunately nothing has changed in MQTT :(

![log-mqtt_2](https://github.com/syssi/esphome-tianpower-bms/assets/19188638/e4f81dd4-a490-4a6d-af46-e1f09b03b00c)

I attach the LOG file in which it seems to me that there is an error:
[logs_bms_compile.txt](https://github.com/syssi/esphome-tianpower-bms/files/11644158/logs_bms_compile.txt)

**Comment by syssi** [comment]
I've fixed the mentioned issue. Please compile & flash the most recent version and provide another log. The log should provide the reason for not pushing measurements. These topics are implemented:

```
tianpower-bms-ble/sensor/tianpower-bms-ble_state_of_charge/state
tianpower-bms-ble/sensor/tianpower-bms-ble_total_voltage/state
```

**Comment by xpinguinx** [comment]
log updated

[logs_bms_compile.txt](https://github.com/syssi/esphome-tianpower-bms/files/11644265/logs_bms_compile.txt)

**Comment by syssi** [comment]
I've pushed a fix. Please give it another try!

**Comment by xpinguinx** [comment]
Good morning Syssi,
Updated register, I remain available
[logs_bms_compile_4.txt](https://github.com/syssi/esphome-tianpower-bms/files/11645000/logs_bms_compile_4.txt)


I also attach the MQTT status
![log-mqtt_4](https://github.com/syssi/esphome-tianpower-bms/assets/19188638/f4ef7658-ef35-4f51-bb54-9de131aede29)

**Comment by syssi** [comment]
The BMS wasn't available this time. May be because it supports just one simultaneous connection and the BLE module was too busy to pick up the new connection:

```
[W][tianpower_bms_ble:126]: [90:A6:BF:93:A0:69] Not connected
[W][tianpower_bms_ble:126]: [90:A6:BF:93:A0:69] Not connected
[W][tianpower_bms_ble:126]: [90:A6:BF:93:A0:69] Not connected
[W][tianpower_bms_ble:126]: [90:A6:BF:93:A0:69] Not connected
```

Could you provide another log?

**Comment by xpinguinx** [comment]
WOW :)

![log-mqtt_5](https://github.com/syssi/esphome-tianpower-bms/assets/19188638/24c99eca-7c93-4704-b91a-26b4f99c6654)



Updated register:
[logs_bms_compile_5.txt](https://github.com/syssi/esphome-tianpower-bms/files/11645176/logs_bms_compile_5.txt)

**Comment by syssi** [comment]
LOL. All measurements are a bit off. ;-) Will be fixed soon.

**Comment by xpinguinx** [comment]
> LOL. Tutte le misurazioni sono un po' fuori. ;-) Verrà risolto presto.

When you have finished the configuration, let me know your paypal address, thanks.

**Comment by syssi** [comment]
The decoding of the measurements is fine now. I would be happy if you could apply some load to your battery so you could check the `current` sensor is working properly. If there is load this value should be positive. If you charge the battery the value should be negative. Please double check the resolution of the sensor. The factor is probably wrong at the moment.

**Comment by xpinguinx** [comment]
Dear Syssi,
finally the goal was a success thanks to your availability!

At the moment I don't have the possibility to check the "current" sensor because the photovoltaic system is in production with the old BMS.
We remain that if I encounter problems I will update you in a few weeks.

Working with you has been pleasant and for this I congratulate you also for your professionalism and knowledge.

**Comment by syssi** [comment]
You are welcome! I tried to contact you via bms@.
