### ISSUE TITLE
BOX BASEN 280 Ah BMS TianPower implemented in home assistant

### ISSUE THREAD

**Issue by PASAR78** [syssi/esphome-tianpower-bms#18]
HI
I wanted to let you know that I was able to make the integration work BMS Tianpower TP-LT55AT.
I used an ESP32 board with CP2102 and restarted the BMS in order to associate the BT.
There are some parameters that give me zero and small things to fix, if you want I'm available to send you the logs, you could make an integration calling it specific for the BASEN bms installed on the BOXES.

**Comment by syssi** [comment]
I'm happy about any input! Feel free to provide some logs! Thanks in advance!
