### ISSUE TITLE
Disable active BLE scans to save some power and RF pollution

### ISSUE THREAD

**Issue by syssi** [syssi/esphome-tianpower-bms#34]
```
esp32_ble_tracker:
  scan_parameters:
    active: false
``` 

@man55 @valdiks @peterhax Could one of you do me a favor and add the additional setting above to your `esp32_ble_tracker` section and give it a try? Is the component still able to talk to your BMS? If yes this setting is recommended to avoid active communication with all discovered BLE devices around.

**Comment by peterhax** [comment]
I have added that to to the ESPHome config, and it still works fine!

**Comment by syssi** [comment]
Thanks for testing!
